name: Setup GCloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-gcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Make setup script executable
      run: chmod +x ./setup_gcloud.sh    

    - name: Run setup script
      run: ./setup_gcloud.sh ${{ secrets.GCP_PROJECT_ID }}
